### ISSUE TITLE
Using Boost-free ASIO

### ISSUE THREAD

**Issue by RobertoMalatesta** [eidheim/Simple-Web-Server#19]
Hi @eidheim,
thanks for your wonderfully clean project.
One question: since you're using only ASIO from Boost, is it planned to avoid Boost dependencies altogether by using the Boost-free version?

Thanks and ciao,

R

**Comment by eidheim** [comment]
I think the boost dependencies will remain for quite a while. Networking is planned in C++-17, however, it takes some time before the various platforms/distros upgrade to a g++ version supporting all these new features (a couple of years after 2017 would be my guess). Also, adding boost::regex as an additional dependency Today, since Red Hat Enterprise Server 7 is still having trouble with C++11 regex support... 

But on the other hand, the Boost libraries are quite well written and maintained, and used by most larger C++ platform independent projects.

**Comment by RobertoMalatesta** [comment]
Taking out regexps as well could be a plus, since gcc 4.9.2 is deadly slow at compiling this code even with --enable-checking=release  (quad-core p5).
Regexps are a nice stylish touch from you, but a simpler system based on url registering could allow more stable compilers (gcc 4.8.x is good enough) to be used as well.
And compilation will be faster.

Forgive me if I'm incorrect or too generic but I just skimmed into your code without going too much in deep.

Ciao,

R
