### ISSUE TITLE
Streaming video and multiple thread issue.

### ISSUE THREAD

**Issue by SumolX** [eidheim/Simple-Web-Server#23]
At the moment I am able to stream a video source to multiple clients (based on the number of client threads issued upon the web server's construction) and keep the session active with the content_timeout set to Zero.  With content_timeout set to any other value the video stream is terminated by the web server since I never exit the anonymous function in order to keep the stream active.

The sudo code below gives you an idea on how its currently implemented.

void StreamVideo(Response& response, Request request)
{
     response << "multipart stream";
     response.flush();

    while (client_sessions_active)
    {
        response << "content length";
        response.flush();
        response.write(video_stream_buffer, video_stream_buffer_size);
        response.flush;
    }
}

Now I have two questions:

1:  Does logic seem correct to you, rest apis usually return from the anonymous functions.  Thus your timeout handling makes sense, but to keep streams active...  I must specify a zero value to content_timeout, but it then is applied to all other requests that could benefit from having a content_timeout specified.  Perhaps a default content_timeout could be via the constructor and overridden upon anonymous function assignment?!?

2:  It seems if I go beyond the 4 client threads, I loose all my active streams and I'm unable to reestablish any new connections to the web server.  Do you have any thoughts on why this happens.  It should be reproducible by never existing an anonymous function with a timeout of Zero.

**Comment by eidheim** [comment]
I am not sure how streaming services are commonly implemented, but maybe WebSockets might be a better way?

If you see the default_resource example, the file sent to the client is divided into smaller parts. When the flush command is run, one part is sent and, additionally, other requests can be handled even though the function has not returned yet (since the flush command temporarily gives control back to the asio thread pool before the anonymous function continues). In this way, more that 4 clients can be handled. 

When it comes to the timeout, I would simply suggest that you have the resources that should have timeouts run in a separate port. At least until I or someone add a function in the response class that one can use to disable/or set a new timeout_content.

**Comment by SumolX** [comment]
The second issue was a mutex deadlock that occurred within my software due to exhausting all 4 threads and on the next session my resource function tried to perform a mutex lock while the thread was already locked.  Thus I'm closing this issue reported.
