### ISSUE TITLE
headers map

### ISSUE THREAD

**Issue by TechnikEmpire** [eidheim/Simple-Web-Server#6]
Pretty sure you're going to have hard to find bugs with your method of parsing headers. By using an unordered_map, you're not going to be able to store multiple headers with the same key identifier, such as set-cookie. Correct way would to use std::multimap with case insensitive comparison on your keys.

**Comment by eidheim** [comment]
You are right. I will fix this soon.

**Comment by TechnikEmpire** [comment]
Yeah also when you're parsing chunked content you've got to check for an accommodate chunk trailers at the end of each chunk length otherwise you're not going to properly advance your position to read the next chunk length or you're going to get an exception or bad length by passing the trailer data into stoull. Also stoull crashes for me gcc 4.9.2 when you get a hex length value such as "a" (10). If you change it to use stringstream and std::hex << and then output the sstream to a size_t you'll get correct values. Sorry I'd fork, fix and issue pull but I'm just too busy, thought I'd share what I know in a quick comment.

**Comment by eidheim** [comment]
I am unable to reproduce the stoull crash. Tested on both gcc-4.9 and clang. Hex values are working using stoull with base 16. Is there a specific site that used chunked transfer that you have a trouble on? Maybe I could see if I get the same result as you if I use the same web site. 

Trailers are currently ignored. These are simply not read since they come after a 0 length chunk. My understanding is that these trailers are almost never used.
